### ISSUE TITLE
Consistência na tipagem

### ISSUE THREAD

**Issue by gusholz** [Vitor-costa-diniz/Apple_Academy#1]
https://github.com/Vitor-costa-diniz/Apple_Academy/blob/a8c7dfa8da00c08ff70f22a91c0a5b7d0784451b/projects/ToDo/ToDo/DefaultAppMessages.swift#LL11C1-L17C3

Para tornar o código mais consistente seria melhor tipar todas as variáveis

**Comment by Vitor-costa-diniz** [comment]
Obrigado pelo feedback, foi um erro que acabei deixando sem querer kkkkk, mas ja concertei.
