### ISSUE TITLE
Utilzacao do Protocolo Codable e Decodable 

### ISSUE THREAD

**Issue by gusholz** [Vitor-costa-diniz/Apple_Academy#2]
https://github.com/Vitor-costa-diniz/Apple_Academy/blob/a8c7dfa8da00c08ff70f22a91c0a5b7d0784451b/projects/ToDo/ToDo/Tasks.swift#L1-L67C1

A titulo de sugestão e simplificação do código, recomendaríamos utilizar esses protocolos (que salvam e leem JSON) para a criação e leitura das Tasks

**Comment by Vitor-costa-diniz** [comment]
A gente começou utilizando o método de salvar em um .txt, e quando os mentores falaram que poderia ser em um arquivo json a gente ja estava com o método de ler e salvar as tarefas em um arquivo de texto, por isso optamos por manter desse jeito, mas obrigado pela sugestão
