### ISSUE TITLE
Utilização de Force Unwrapping( ! )

### ISSUE THREAD

**Issue by Pedro-HS-Rodrigues** [Vitor-costa-diniz/Apple_Academy#3]
Durante o código, mais precisamente no ManipulateArray.swift, a forma escolhida para remover o valor Opcional( ) das leituras do Readline( ) não é recomendada, a utilização do ! faz com que o código não tenha segurança, a forma mais indicada seria o uso do guard let tanto para questão de segurança como organização. A mudança seria assim: (Exemplo de mudança na primeira função)

guard let title  = readline() else {
return print("Digite a descrição da tarefa: ",terminator:"")
}

Desta forma a variável tem o opcional removido e a sua utilização fica disponível em todo o bloco de código da função.

**Comment by Vitor-costa-diniz** [comment]
Obrigado pelo feedback 😄, irei ajeitar esse problema.
