### ISSUE TITLE
Uso do forceUnwrapping

### ISSUE THREAD

**Issue by GabrielCarvalhoM** [Vitor-costa-diniz/Apple_Academy#5]
Código no geral ficou muito bom, a lógica e conceitos um pouco mais avançados foram muito bem utilizados, único ponto que vejo a melhoria, seria tratamento dos casos de optionals, no lugar do desempacotamento forçado, tratando de forma mais individual e passando mensagens de erro mais bem definidas pro usuário.

**Comment by Vitor-costa-diniz** [comment]
Brigado pela dica, ajeitei no código para usar o safe unwrapping.
